version: "3"
services:
  ilivalidator:
    image: sogis/ilivalidator-web-service-micronaut:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    ports:
      - "4000:8080"
